{% set name = "reprounzip" %}
{% set version = "1.0.16" %}
{% set sha256 = "699065cf81e3769f214ff9a1c8ab65415bf77ec4cc7c995b4e4cdfb75a1e43d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools  # for pkg_resources
    - pyyaml
    - requests
    - rpaths >=0.8
    - usagestats >=0.3

test:
  imports:
    - reprounzip.main
    - reprounzip.unpackers.default

  commands:
    - reprounzip --help

about:
  home: http://github.com/ViDA-NYU/reprozip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Linux tool enabling reproducible experiments (unpacker)'
  description: |
    ReproZip is a tool aimed at simplifying the process of creating reproducible
    experiments from command-line executions, a frequently-used common
    denominator in computational science. It tracks operating system calls and
    creates a package that contains all the binaries, files and dependencies
    required to run a given command on the author's computational environment
    (packing step). A reviewer can then extract the experiment in his
    environment to reproduce the results (unpacking step).
  doc_url: https://docs.reprozip.org/
  dev_url: https://github.com/ViDA-NYU/reprozip

extra:
  recipe-maintainers:
    - remram44
