travis:
  secure:
    BINSTAR_TOKEN: EVu0L1hEyzsuOcZXLfc//bwIvgjfSblj6rFSHzg1UjpkzLUszhA8+hZC/hYbRIdthGKt2nEnF1rAwIoJG6dV/QRpq1ApA4+cYga65x84eBDdnDmR1pjd04BnlkLWpPmkYWabi73dr1jjHj0nKLTXgdX8JIdW3dVgQqof7da74EMdxXenXdJzAyUbjJGNot79w4jQQpHGGAhNQAvWh3B+Ypx/GSFjbWvxgglwlOnn6sQAJhRkLTuYD4ymmXt+SSRYBarTEVWoSzQVnt98mQkOGMdbRxIm95oqpolCWFR4RM3cjuxU9NWzLeor8S0qgXP0p/hI8qy1FKX0GcdUhWmAz4uQ7LuRg4mEMIT7576qXH6sKUy/f5Xy2njGwLBbe/LhOqlEERmF7C+N2jWu8PaJtfXLOlE2b/a7dUE44qDMfLnxXtAKa9Gw3X3OZVNui/AKrFC460uHDvRIrXwYp8y+5jqfYAgOLQnHXtXA3MueEFeIvNXnNxn920KanHHIXhzTs/LsGvl5xl5/jZhhKVukQSuM9Ze8eulhi3IMtvuqEXfXazGw21IqjWnyPjBa1tiDmj0Fv88IbXn1/dESDc97sbxnICSNlc1yEX37/C00LheI4G1cBYB0QIBiUpPCgJ574pBZThWxupt+nDsMJh+dLHQmxYt/lx89L2L15bbEoMg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
