travis:
  secure:
    BINSTAR_TOKEN: Rh6q2zvsUCB2S6NCIGmeocyvgWRc1FJbuUMZc5pawuBMA9ZWVqv6lJXe0LIv+7tDrv+F+Mg9dH37T16Y1d9LEWPSE/olwLEQn464NGIeKrWD6Oxx/yirFTjWbTCsrUY0AEmqHZhBfEmUFD/qAZNf3pNQATzyfnSWwZM3b3tNi2qTglLoJAD+qlYUsjMaIZduvQK74kza748HgXRJ6yB2tOEPsHNAnr5qXKidFoka1k4UOQ3D1b1IFeY7Voi7bGd9u61crPPJ6QxG/xCyo8a92le2HQpjZW/a08FK+hCoZRwwS2AAcDmml445M4e4nyZcyON0+0IiRyfqIJdbQPl7cU6ftfAHRQGUond1KGBKF5UKn9RIF4cv113YVbDW0Ji/CWVpYKN+QvsiiLGdA3STiGsPx0tGUXJGM36N5ByjFh5dwz1gxtJapSaOS74a7SaKpxV4NZf9elzj3qVekGXTE1rWJT5SmDh8LsMKHJkPZfYnHQpc9SLnc2k4cVVKf1RNemUWHgt6I6aYlaypold8cz7VAhlzyHn2ipkQWIG1iv04y6PIKpcNaeChIDRlaW5pcZoY14W6MOSmx+ZzwG1Y2w3VOVndsI1rBMvjLombwjvbeVCqdJGQ/QTvt8q+9mqBr2xRI43KjBOSHbQ8LK1uEkdpbiMx4TcAlx2zYqQT0zk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
